doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        schema_manager_factory: doctrine.dbal.schema_manager_factory.sqlite

        # IMPORTANT: Empêcher l'utilisation des commandes non supportées par SQLite
        schema_filter: ~^(?!sqlite_)~

        # Pour éviter l'erreur getListDatabasesSQL
        override_url: true

        # Configuration spécifique pour les migrations
        driver_options:
            foreign_key_constraints: true
            ignore_platform_unsupported_methods: true # Cette option permet d'ignorer les méthodes non supportées

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
