knpu_oauth2_client:
    clients:
        oidc:
            type: generic
            client_id: '%env(OIDC_CLIENT_ID)%'
            client_secret: '%env(OIDC_CLIENT_SECRET)%'
            redirect_route: 'oidc_check'
            provider_class: League\OAuth2\Client\Provider\GenericProvider
            provider_options:
                urlAuthorize: '%env(OIDC_URL_AUTHORIZE)%'
                urlAccessToken: '%env(OIDC_URL_ACCESS_TOKEN)%'
                urlResourceOwnerDetails: '%env(OIDC_URL_RESOURCE_OWNER)%'