services:
  php:
    build:
      context: .
      dockerfile: ./docker/images/Dockerfile
    container_name: bd
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - SYMFONY_ENV=dev

