services:
  php:
    build:
      context: .
      dockerfile: ./docker/images/Dockerfile
    container_name: php-pokedex
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - SYMFONY_ENV=dev
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-pokedex
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pokedex
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
