name: CI Build Without Env Files

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APP_ENV: prod
      APP_DEBUG: 0
      APP_SECRET: ${{ secrets.APP_SECRET || 'github_ci_temporary_secret' }}
      MESSENGER_TRANSPORT_DSN: doctrine://default
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data/bd.sqlite"
      APP_NO_DOT_ENV: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl, pdo_sqlite
        tools: symfony-cli, composer:v2

    - name: Install PHP dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Build assets
      run: |
        yarn install
        yarn build

    - name: Test application bootstrap
      run: php bin/console cache:clear --no-warmup

    - name: Cache build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-assets
        path: public/build/